import "react-responsive-carousel/lib/styles/carousel.min.css";
import "./styles/globals.css";
import "./styles/home.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </head>
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
