import "react-responsive-carousel/lib/styles/carousel.min.css";
import "./styles/globals.css";
import "./styles/home.css";
import "./styles/about.css";
import "./styles/register.css";
import "./styles/services.css";
import "./styles/header.css";
import "./styles/login.css";
import Header from "@/components/Header";
import ChatbotWidget from "@/components/ChatbotWidget";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "../components/context/UserContext";

export const metadata = {
  title: "Elearny",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </head>
      <body className="antialiased">
        <UserProvider>
          <Header />
          {children}
          <ChatbotWidget />
          <Toaster position="bottom-right" reverseOrder={false} />
        </UserProvider>
      </body>
    </html>
  );
}
